Add reconstrcut and make_direct_map methods
andyalm/faissmask pull request #1
Opened 2021-10-05 03:54 UTC by gregsinclair42

Exposes some useful functionality to reconstruct a vector already in the index. Advantage to this is you don't have to read from dynamo if the vector is already in the index.

2021-10-06 19:29 UTC, andyalm commented on FaissMask/Internal/IndexSafeHandle.cs
> +        public float[] ReconstructVector(long key, int dimensions)
Thinking about the interface of this method, it seems a bit odd to have to pass in the size of the vector. Is there a faiss api that can be called that can return the size of a vector with a particular key? If so, it would be nice to omit that parameter from this method signature.

2021-10-06 22:04 UTC, gregsinclair42 commented on FaissMask/Internal/IndexSafeHandle.cs
> +        public float[] ReconstructVector(long key, int dimensions)
there's a getter for the `d` property I should be able to use. One moment...

2021-10-06 22:50 UTC, andyalm requested changes

2021-10-06 22:50 UTC, andyalm commented on FaissMask/Internal/IndexSafeHandle.cs
> +            var dimensions = NativeMethods.faiss_Index_d(this);
Can this be `var dimensions = Dimensions` so we re-use the property definition instead?
```suggestion
            var dimensions = Dimensions;
```

2021-10-06 22:50 UTC, andyalm commented on FaissMask/Internal/IndexSafeHandle.cs
> +            var dimensions = NativeMethods.faiss_Index_d(this);
```suggestion
            var dimensions = Dimensions;
```
Can we re-use the property definition?

2021-10-07 16:46 UTC, gregsinclair42 commented on FaissMask/Internal/IndexSafeHandle.cs
> +        public float[] ReconstructVector(long key, int dimensions)
Updated

2021-10-07 16:46 UTC, gregsinclair42 commented on FaissMask/Internal/IndexSafeHandle.cs
> +            var dimensions = NativeMethods.faiss_Index_d(this);
Updated

2021-10-07 22:54 UTC, andyalm approved these changes

2021-10-07 22:54 UTC, merged